site_name: OWASP Security Champions Guide
site_description: OWASP Security Champions Guide
#repo_name: OWASP/SCG
#repo_url: https://github.com/OWASP/SCG
copyright: This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution Share Alike 4.0 International license</a>.
docs_dir: docs
theme:
  name: material
  language: en
  logo: assets/OWASP_Logo_Transp.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Welcome
        - News
  - offline

markdown_extensions:
  - attr_list

nav:
  - Introduction: index.md
  - Manifesto: 'Manifesto.md'

  - Principles:
    - 1. Be passionate about security: 'Be_passionate_about_security.md'
    - 2. Start with a clear vision for your program: 'Start_with_a_clear_vision_for_your_program.md'
    - 3. Secure management support: 'Secure_management_support.md'
    - 4. Nominate a dedicated captain: 'Nominate_a_dedicated_captain.md'
    - 5. Trust your champions: 'Trust_your_champions.md'
    - 6. Create a community: 'Create_a_community.md'
    - 7. Promote knowledge sharing: 'Promote_knowledge_sharing.md'
    - 8. Reward responsibility: 'Reward_responsibility.md'
    - 9. Invest in your champions: 'Invest_in_your_champions.md'
    - 10. Anticipate personnel changes: 'Anticipate_personnel_changes.md'

  - Maturity model:
    - Introduction: maturitymodel/index.md
    - Phases:
      - 1. Initial: 'maturitymodel/phases/mm_initial.md'
      - 2. Managed: 'maturitymodel/phases/mm_managed.md'
      - 3. Defined: 'maturitymodel/phases/mm_defined.md'
      - 4. Quantitatively Managed: 'maturitymodel/phases/mm_quantitatively_managed.md'
      - 5. Optimizing: 'maturitymodel/phases/mm_optimizing.md'
    - Principles:
      - 1. Be passionate about security: 'maturitymodel/principles/mm_Be_passionate_about_security.md'
      - 2. Start with a clear vision for your program: 'maturitymodel/principles/mm_Start_with_a_clear_vision_for_your_program.md'
      - 3. Secure management support: 'maturitymodel/principles/mm_Secure_management_support.md'
      - 4. Nominate a dedicated captain: 'maturitymodel/principles/mm_Nominate_a_dedicated_captain.md'
      - 5. Trust your champions: 'maturitymodel/principles/mm_Trust_your_champions.md'
      - 6. Create a community: 'maturitymodel/principles/mm_Create_a_community.md'
      - 7. Promote knowledge sharing: 'maturitymodel/principles/mm_Promote_knowledge_sharing.md'
      - 8. Reward responsibility: 'maturitymodel/principles/mm_Reward_responsibility.md'
      - 9. Invest in your champions: 'maturitymodel/principles/mm_Invest_in_your_champions.md'
      - 10. Anticipate personnel changes: 'maturitymodel/principles/mm_Anticipate_personnel_changes.md'

  - Get involved: 'Get_involved.md'
  - Blog: blog/index.md